apiVersion: v1
kind: Service
metadata:
  name: {{.app}}
spec:
  selector:
    app: {{.app}}
    tier: {{.tier}}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  type: LoadBalancer
---
# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: saleor-dashboard
#   namespace: default
#   selfLink: /api/v1/namespaces/default/configmaps/saleor-dashboard
# data:
#   config.js: |- 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.app}}
    tier: {{.tier}}
  name: {{.app}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.app}}
  template:
    metadata:
      labels:
        app: {{.app}}
        tier: {{.tier}}
    spec:
      containers:
      - image: {{.image}}
        imagePullPolicy: IfNotPresent
        name: {{.app}}
        ports:
        - containerPort: 9000
          protocol: TCP
      terminationGracePeriodSeconds: 30
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
 